#ifndef REMOTEDICTIONARY_ERROR_CODES_H
#define REMOTEDICTIONARY_ERROR_CODES_H

#define RET_OK                    0x0000
#define RET_MEMORY_ALLOC_ERROR    0x0001
#define RET_INVALID_PARAM         0x0002
#define RET_SERVER_LISTEN_ERROR   0x0003



#endif //REMOTEDICTIONARY_ERROR_CODES_H
